### ISSUE TITLE
Creating an index does not return despite promise getting processed

### ISSUE THREAD

**Issue by afroisalreadyinu** [elasticsearch/elasticsearch-js#177]
Here is a simple snippet which I would expect to create an index and return normally, after printing `{acknowledged: true }`: 

```
var es = require('elasticsearch');

var es_client = new es.Client({host: "localhost:9200"});
var breaker = Math.floor((Math.random() * 100) + 1);

var create_promise = es_client.indices.create({index: "test-index-" + breaker});
create_promise.then(function(x) {
    console.log(x);
}, function(err) { console.log(err);});
```

What happens instead is that the index is created, but the script hangs, and the promise does not return.

Tested on ElasticSearch versions 1.2.4 and 1.4.2, and node version 0.10.24. I also asked this question on StackOverflow: http://stackoverflow.com/questions/27861953/creating-an-index-with-elasticsearch-javascript-client-promise-does-not-return

**Comment by spenceralger** [comment]
Hey @afroisalreadyinu,

By default the client keeps persistent connections to elasticsearch so that subsequent requests to the same node are much faster. This has the side effect of preventing node from closing normally until `client.close()` is called. You could either add that call to your callback, or disable keepalive connections by adding `keepAlive: false` to your client config.

Hope this helps, reflected this answer on SO.

**Comment by afroisalreadyinu** [comment]
Thanks, this is certainly the right solution. It is conspicuously missing from the documentation, though; there is mention of it neither on the quick start page, nor on api conventions, nor on the api listing page. One can see it on the configuration page, but it is mentioned once without pointing out the importance of this parameter. Wouldn't it make sense to mention it in a more prominent place?

**Comment by spenceralger** [comment]
Where would you suggest mentioning it?

**Comment by afroisalreadyinu** [comment]
I think "API Conventions" would be a good place to mention it, since it is referenced by the API page, and one has to read it through to actually be able to use the library.

Thanks a lot!
