### ISSUE TITLE
Unable to download the browser build

### ISSUE THREAD

**Issue by rgorel** [elasticsearch/elasticsearch-js#189]
https://download.elasticsearch.org/elasticsearch/elasticsearch-js/elasticsearch-js-3.1.3.zip - this link is posted in your readme and on the official site, and returns error 403. Where can I download the latest stable build?

**Comment by juliendangers** [comment]
see #188
correct link is https://download.elasticsearch.org/elasticsearch/elasticsearch-js/elasticsearch-js-3.1.1.zip

**Comment by rgorel** [comment]
that works, thanks
